package com.citigo.model;
// Generated Apr 22, 2016 11:54:43 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bill generated by hbm2java
 */
@Entity
@Table(name = "BILL", schema = "QLBH_DB")
public class Bill implements java.io.Serializable {

	private BigDecimal id;
	private Customer customer;
	private Double totalmoney;
	private Date dateBill;
	private BigDecimal status;
	private Set<Billdetail> billdetails = new HashSet<Billdetail>(0);

	public Bill() {
	}

	public Bill(BigDecimal id) {
		this.id = id;
	}

	public Bill(BigDecimal id, Customer customer, Double totalmoney, Date dateBill, BigDecimal status,
			Set<Billdetail> billdetails) {
		this.id = id;
		this.customer = customer;
		this.totalmoney = totalmoney;
		this.dateBill = dateBill;
		this.status = status;
		this.billdetails = billdetails;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTOMER_ID")
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "TOTALMONEY", precision = 126, scale = 0)
	public Double getTotalmoney() {
		return this.totalmoney;
	}

	public void setTotalmoney(Double totalmoney) {
		this.totalmoney = totalmoney;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_BILL", length = 7)
	public Date getDateBill() {
		return this.dateBill;
	}

	public void setDateBill(Date dateBill) {
		this.dateBill = dateBill;
	}

	@Column(name = "STATUS", precision = 22, scale = 0)
	public BigDecimal getStatus() {
		return this.status;
	}

	public void setStatus(BigDecimal status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bill")
	public Set<Billdetail> getBilldetails() {
		return this.billdetails;
	}

	public void setBilldetails(Set<Billdetail> billdetails) {
		this.billdetails = billdetails;
	}

}
