package com.citigo.model;
// Generated Apr 22, 2016 11:54:43 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Company generated by hbm2java
 */
@Entity
@Table(name = "COMPANY", schema = "QLBH_DB")
public class Company implements java.io.Serializable {

	private BigDecimal id;
	private String name;
	private String address;
	private String tel;
	private String fax;

	public Company() {
	}

	public Company(BigDecimal id) {
		this.id = id;
	}

	public Company(BigDecimal id, String name, String address, String tel, String fax) {
		this.id = id;
		this.name = name;
		this.address = address;
		this.tel = tel;
		this.fax = fax;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 500)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ADDRESS", length = 500)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "TEL", length = 20)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "FAX", length = 20)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

}
