package com.citigo.model;
// Generated Apr 22, 2016 11:54:43 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Contact generated by hbm2java
 */
@Entity
@Table(name = "CONTACT", schema = "QLBH_DB")
public class Contact implements java.io.Serializable {

	private BigDecimal id;
	private String name;
	private String company;
	private String address;
	private String tel;
	private String mail;
	private String detail;
	private String datesend;

	public Contact() {
	}

	public Contact(BigDecimal id) {
		this.id = id;
	}

	public Contact(BigDecimal id, String name, String company, String address, String tel, String mail, String detail,
			String datesend) {
		this.id = id;
		this.name = name;
		this.company = company;
		this.address = address;
		this.tel = tel;
		this.mail = mail;
		this.detail = detail;
		this.datesend = datesend;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "COMPANY", length = 500)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "ADDRESS", length = 500)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "TEL", length = 20)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "MAIL", length = 100)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "DETAIL", length = 500)
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	@Column(name = "DATESEND", length = 0)
	public String getDatesend() {
		return this.datesend;
	}

	public void setDatesend(String datesend) {
		this.datesend = datesend;
	}

}
