package com.citigo.model;
// Generated Apr 22, 2016 11:54:43 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Groupproduct generated by hbm2java
 */
@Entity
@Table(name = "GROUPPRODUCT", schema = "QLBH_DB")
public class Groupproduct implements java.io.Serializable {

	private BigDecimal id;
	private String name;
	private String content;
	private String image;
	private BigDecimal status;
	private BigDecimal orderGp;
	private Set<Product> products = new HashSet<Product>(0);

	public Groupproduct() {
	}

	public Groupproduct(BigDecimal id) {
		this.id = id;
	}

	public Groupproduct(BigDecimal id, String name, String content, String image, BigDecimal status, BigDecimal orderGp,
			Set<Product> products) {
		this.id = id;
		this.name = name;
		this.content = content;
		this.image = image;
		this.status = status;
		this.orderGp = orderGp;
		this.products = products;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "CONTENT", length = 200)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "IMAGE", length = 200)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "STATUS", precision = 22, scale = 0)
	public BigDecimal getStatus() {
		return this.status;
	}

	public void setStatus(BigDecimal status) {
		this.status = status;
	}

	@Column(name = "ORDER_GP", precision = 22, scale = 0)
	public BigDecimal getOrderGp() {
		return this.orderGp;
	}

	public void setOrderGp(BigDecimal orderGp) {
		this.orderGp = orderGp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupproduct")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
