package com.citigo.model;
// Generated Apr 22, 2016 11:54:43 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "MENU", schema = "QLBH_DB")
public class Menu implements java.io.Serializable {

	private BigDecimal id;
	private String name;
	private String link;
	private BigDecimal orderMn;
	private BigDecimal parentid;

	public Menu() {
	}

	public Menu(BigDecimal id) {
		this.id = id;
	}

	public Menu(BigDecimal id, String name, String link, BigDecimal orderMn, BigDecimal parentid) {
		this.id = id;
		this.name = name;
		this.link = link;
		this.orderMn = orderMn;
		this.parentid = parentid;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "LINK", length = 200)
	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	@Column(name = "ORDER_MN", precision = 22, scale = 0)
	public BigDecimal getOrderMn() {
		return this.orderMn;
	}

	public void setOrderMn(BigDecimal orderMn) {
		this.orderMn = orderMn;
	}

	@Column(name = "PARENTID", precision = 22, scale = 0)
	public BigDecimal getParentid() {
		return this.parentid;
	}

	public void setParentid(BigDecimal parentid) {
		this.parentid = parentid;
	}

}
