package com.citigo.model;
// Generated Apr 22, 2016 11:54:43 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "PRODUCT", schema = "QLBH_DB")
public class Product implements java.io.Serializable {

	private BigDecimal id;
	private Groupproduct groupproduct;
	private String name;
	private String detail;
	private Double price;
	private String image;
	private Double pricenew;
	private Date datePd;
	private BigDecimal orderPd;
	private BigDecimal status;
	private String suppiler;
	private BigDecimal quantity;
	private Set<Billdetail> billdetails = new HashSet<Billdetail>(0);

	public Product() {
	}

	public Product(BigDecimal id) {
		this.id = id;
	}

	public Product(BigDecimal id, Groupproduct groupproduct, String name, String detail, Double price, String image,
			Double pricenew, Date datePd, BigDecimal orderPd, BigDecimal status, String suppiler, BigDecimal quantity,
			Set<Billdetail> billdetails) {
		this.id = id;
		this.groupproduct = groupproduct;
		this.name = name;
		this.detail = detail;
		this.price = price;
		this.image = image;
		this.pricenew = pricenew;
		this.datePd = datePd;
		this.orderPd = orderPd;
		this.status = status;
		this.suppiler = suppiler;
		this.quantity = quantity;
		this.billdetails = billdetails;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GROUPPRODUCT_ID")
	public Groupproduct getGroupproduct() {
		return this.groupproduct;
	}

	public void setGroupproduct(Groupproduct groupproduct) {
		this.groupproduct = groupproduct;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DETAIL", length = 200)
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	@Column(name = "PRICE", precision = 126, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Column(name = "IMAGE", length = 500)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "PRICENEW", precision = 126, scale = 0)
	public Double getPricenew() {
		return this.pricenew;
	}

	public void setPricenew(Double pricenew) {
		this.pricenew = pricenew;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_PD", length = 7)
	public Date getDatePd() {
		return this.datePd;
	}

	public void setDatePd(Date datePd) {
		this.datePd = datePd;
	}

	@Column(name = "ORDER_PD", precision = 22, scale = 0)
	public BigDecimal getOrderPd() {
		return this.orderPd;
	}

	public void setOrderPd(BigDecimal orderPd) {
		this.orderPd = orderPd;
	}

	@Column(name = "STATUS", precision = 22, scale = 0)
	public BigDecimal getStatus() {
		return this.status;
	}

	public void setStatus(BigDecimal status) {
		this.status = status;
	}

	@Column(name = "SUPPILER", length = 500)
	public String getSuppiler() {
		return this.suppiler;
	}

	public void setSuppiler(String suppiler) {
		this.suppiler = suppiler;
	}

	@Column(name = "QUANTITY", precision = 22, scale = 0)
	public BigDecimal getQuantity() {
		return this.quantity;
	}

	public void setQuantity(BigDecimal quantity) {
		this.quantity = quantity;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Billdetail> getBilldetails() {
		return this.billdetails;
	}

	public void setBilldetails(Set<Billdetail> billdetails) {
		this.billdetails = billdetails;
	}

}
