var students=[{name:'Jonh',clas:'TH11A'},
              {name:'Hege',clas:'TH11B'},
              {name:'Kai',clas:'TH12A'},
              {name:'Jonh',clas:'TH11A'},
              {name:'Jonh',clas:'TH11A'},
              {name:'Jonh',clas:'TH11A'},
              {name:'Jonh',clas:'TH11A'},
              {name:'Jonh',clas:'TH11A'},
              {name:'Jonh',clas:'TH11A'},
              {name:'Jonh',clas:'TH11A'},
              {name:'Jonh',clas:'TH11A'},
              {name:'Jonh',clas:'TH11A'},
              {name:'Jonh',clas:'TH11A'},
              {name:'Jonh',clas:'TH11A'},];